# Generated by Django 6.0.2 on 2026-02-16 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleV2', '0002_user_otp_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default=False, max_length=254),
        ),
    ]
