# Generated by Django 6.0.2 on 2026-02-25 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student2',
        ),
    ]
