# Generated by Django 6.0.2 on 2026-02-25 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('application_deadline', models.DateField()),
                ('application_link', models.URLField(blank=True, null=True)),
                ('company_website_url', models.URLField(blank=True, null=True)),
                ('company_facebook_url', models.URLField(blank=True, null=True)),
                ('company_linkedin_url', models.URLField(blank=True, null=True)),
                ('company_phone_no', models.CharField(blank=True, max_length=30, null=True)),
                ('company_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['application_deadline', '-created_at'],
            },
        ),
    ]
